services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    restart: unless-stopped
    ports:
      - "${COUCHDB_PORT}:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    
    volumes:
      - ./volumes/couchdb:/opt/couchdb/data