services:
  homecontrol:
    image: ghcr.io/roy752/homecontrol:latest

    container_name: homecontrol

    ports:
      - "${HOMECONTROL_PORT}:8000"
    
    restart: unless-stopped

    environment:
      - TZ: Asia/Seoul