name: Deploy Homelab

on:
    push:
      branches:
        - master
    workflow_dispatch:
    repository_dispatch:
        types: [deploy]
    
jobs:
    deploy:
        runs-on: self-hosted

        steps:
          - name: Checkout repository
            shell: powershell
            run: |
              Set-Location C:\homelab

              git fetch origin
              git checkout master
              git reset --hard origin/master
              git clean -fd

          - name: Update Docker containers
            shell: powershell
            run: |
              Set-Location C:\homelab

              docker compose pull
              docker compose up -d --env-file .env --env-file ..\homelab_secret\.env.local --remove-orphans

              docker image prune -f